let AG_URL = "ADD_AGENCY_URL_HERE";
let AG_IP = "ADD_AGENCY_IP_HERE";
let AG_PORT = "ADD_AGENCY_PORT_HERE";

let EA_URL = "ADD_ENTERPRISE_AGENT_URL_HERE";
let EA_username = "username";
let EA_password = "secret";
let EA_DID = "ENTERPRISE_AGENT_PUBLIC_DID";

let SERVICE_ENDPOINT = "SERVICE_ENDPOINT_URL (i.e Nightscout)";
let SERVICE_PORT = "";
let SERVICE_ENDPOINT_TOKEN = "SERVICE_ACCESS_TOKEN";

module.exports = {
  AG_URL,
  EA_URL,
  EA_username,
  EA_password,
  EA_DID,
  SERVICE_ENDPOINT,
  SERVICE_PORT,
  SERVICE_ENDPOINT_TOKEN,
  AG_IP,
  AG_PORT,
};
